name: Totesys Test and Deploy
run-name: ${{ github.actor }} has triggered testing on push 🚀
on: [push]
jobs:
  run-tests:

    runs-on: ubuntu-latest
    environment: dev
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
  
      - name: Setup test database
        run: psql -f data/seed_mock_db.sql -p 5432 -h localhost -U postgres
        env: 
          PGPASSWORD: postgres
      
      - name: Setup test warehouse
        run: psql -f data/test_warehouse_db.sql -p 5432 -h localhost -U postgres
        env: 
          PGPASSWORD: postgres

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run project setup
        run: make run-setup
        env: 
          DBUSER : postgres
          DBNAME : mock_totesys
          DBPASSWORD : postgres 
          PORT: 5432
          HOST : localhost
      
      - name: Run initial tests
        run: make unit-test-initial
        env: 
          DBUSER : postgres
          DBNAME : mock_totesys
          DBPASSWORD : postgres 
          PORT: 5432
          HOST : localhost
      
      - name: Run load tests
        run: make unit-test-load
        env: 
          DBUSER : postgres
          DBNAME : mock_warehouse
          DBPASSWORD : postgres 
          PORT: 5432
          HOST : localhost

      - run: echo "🍏 This job's status is ${{ job.status }}."

    
  terraform:

    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    needs: postgres-run-tests

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout out repository code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-2"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt 

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -input=false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Prepare lambda directories
      run: |
        mkdir -p lambda/ingestion/src/ingestion
        mkdir -p lambda/transform/src/transform
        mkdir -p lambda/load/src/load

    - name: Install dependancies 
      run: |
        pip install -r src/ingestion/ingestion_requirements.txt -t lambda/ingestion/
        pip install -r src/transform/transform_requirements.txt -t lambda/transform/
        pip install -r src/load/load_requirements.txt -t lambda/load/
    
    - name: Copying source code and utils into lambda folder
      run: |
            cp -r src/ingestion/* lambda/ingestion/src/ingestion/
            cp -r src/ingestion/* lambda/ingestion/
            cp -r utils lambda/ingestion/
            cp -r src/transform/* lambda/transform/src/transform
            cp -r src/transform/* lambda/transform/
            cp -r utils lambda/transform/
            cp -r src/load/* lambda/load/src/load
            cp -r src/load/* lambda/load/
            cp -r utils lambda/load/

    - name: Zip up lambda package
      run: |
            cd lambda/ingestion/
            zip -r ingestion.zip .
            cd ../transform
            zip -r transform-lambda.zip .
            cd ../load
            zip -r load-lambda.zip . 
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Terraform Apply Initial Steps
      working-directory: terraform
      run: |
          terraform apply -auto-approve -input=false
          aws s3 cp ../lambda/ingestion/ingestion.zip "s3://$(terraform output -raw code_bucket_name)"
          aws s3 cp ../lambda/transform/transform-lambda.zip "s3://$(terraform output -raw code_bucket_name)"
          aws s3 cp ../lambda/load/load-lambda.zip "s3://$(terraform output -raw code_bucket_name)"

    - name: Terraform Apply In Full
      working-directory: terraform
      run: | 
          terraform apply -auto-approve -input=false -var="deploy_lambda_bool=true"
